/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace RakNet {

public enum FT_MessageTypesNode {
  NODE_FT_None = 0,
  NODE_FT_TEST1,
  NODE_FT_UNITDATA,
  NODE_FT_UNITDATA_LIST
}

}
