/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace RakNet {

using System;
using System.Runtime.InteropServices;

public class FT_ConnectProcessResultHandlerTest : FT_ConnectProcessResultHandler {
  private HandleRef swigCPtr;

  internal FT_ConnectProcessResultHandlerTest(IntPtr cPtr, bool cMemoryOwn) : base(RakNetPINVOKE.FT_ConnectProcessResultHandlerTest_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(FT_ConnectProcessResultHandlerTest obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~FT_ConnectProcessResultHandlerTest() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          RakNetPINVOKE.delete_FT_ConnectProcessResultHandlerTest(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public override void OnConnectedToServer() {
    RakNetPINVOKE.FT_ConnectProcessResultHandlerTest_OnConnectedToServer(swigCPtr);
  }

  public override void OnFailedToConnect() {
    RakNetPINVOKE.FT_ConnectProcessResultHandlerTest_OnFailedToConnect(swigCPtr);
  }

  public override void OnLostConnection() {
    RakNetPINVOKE.FT_ConnectProcessResultHandlerTest_OnLostConnection(swigCPtr);
  }

  public override void OnDisconnectedFromServer() {
    RakNetPINVOKE.FT_ConnectProcessResultHandlerTest_OnDisconnectedFromServer(swigCPtr);
  }

  public override void DebugReceive(int flag) {
    RakNetPINVOKE.FT_ConnectProcessResultHandlerTest_DebugReceive(swigCPtr, flag);
  }

  public override void ReceiveLog() {
    RakNetPINVOKE.FT_ConnectProcessResultHandlerTest_ReceiveLog(swigCPtr);
  }

}

}
