/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace RakNet {

public enum FT_EUnit {
  FT_EUnit_None = 0,
  FT_EUnit_Trees = 1,
  FT_EUnit_Stone = 2
}

}
