/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace RakNet {

public enum FT_MessageTypes {
  ID_FT_TEST1 = DefaultMessageIDTypes.ID_USER_PACKET_ENUM+1,
  ID_SERVER_LOGIN
}

}
